env:
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - airbnb-base
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  import/no-unresolved": [0, {commonjs: true, amd: true}]


