env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - airbnb-base
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
  